# Generated by Django 2.0.7 on 2019-11-07 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191107_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(related_name='chat_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
