# Generated by Django 2.0.7 on 2019-11-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191107_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='users_count',
            field=models.IntegerField(default=0),
        ),
    ]
