# Generated by Django 2.0.7 on 2019-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20191113_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='filename',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
